spring:
  main:
    show_banner: false
  # Configured for Hadoop single-node running on localhost. Replace with property values reflecting your
  # actual Hadoop cluster when running in a distributed environment.
  hadoop:
    fsUri: hdfs://localhost:8020
    resourceManagerHost: localhost
    resourceManagerPort: 8032
    resourceManagerSchedulerAddress: localhost:8030
  # Configured for Redis running on localhost. Replace at least host property when running in a
  # distributed environment.
  redis:
    port: 6379
    host: localhost
  # Configured for an embedded in-memory H2 database. Replace the datasource configuration with properties
  # matching your preferred database to be used instead, if needed, or when running in a distributed environment.
  datasource:
    url: jdbc:h2:tcp://localhost:9092/mem:dataflow
    username: sa
    password:
    driverClassName: org.h2.Driver
#  yarn:
#    hostdiscovery:
#      pointToPoint: false
#      loopback: false
#      preferInterface: ['eth', 'en']
#      matchIpv4: 192.168.0.0/24
#      matchInterface: eth\\d*
#dataflow:
#  yarn:
#    app:
#      streamappmaster:
#        memory: 512m
#        virtualCores: 1
#      streamcontainer:
#        priority: 5
#        memory: 256m
#        virtualCores: 1
#        javaOpts: "-Xms64m -Xmx256m"
#      taskappmaster:
#        memory: 512m
#        virtualCores: 1
#      taskcontainer:
#        priority: 10
#        memory: 256m
#        virtualCores: 1
#        javaOpts: "-Xms64m -Xmx256m"
