server:
  port: ${dataflow.server.port:9393}
security:
  basic:
    enabled: false
management:
  contextPath: /management
info:
  app:
    name: "@project.artifactId@"
    description: "@project.description@"
    version: "@project.version@"
spring:
  main:
    banner_mode: "off"
  application:
    name: spring-cloud-dataflow-server-yarn
  cloud:
    dataflow:
      yarn:
        version: "@project.version@"
    deployer:
      yarn:
        version: "@spring-cloud-deployer-yarn.version@"
